services:
  playwright:
    depends_on:
      - api
    build:
      dockerfile: ./docker/test.Dockerfile
      context: ../
    environment:
      - PRIVATE_KEY
      - DATABASE_URL
      - DATABASE_TOKEN
      - DATABASE_CONNECTION
      - SALT
      - MAGIC_SECRET_KEY
      - SENTRY_DSN
      - MAILCHIMP_API_KEY
      - LOGTAIL_TOKEN
      - CLUSTER_API_URL
      - CLUSTER_BASIC_AUTH_TOKEN
