version: '3.6'
services:
  post_rest:
    image: postgrest/postgrest:v9.0.0
    depends_on:
      - db
    environment:
      PGRST_DB_URI: $DATABASE_CONNECTION
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres
      PGRST_JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
  db_init:
    restart: on-failure
    build:
      dockerfile: 'docker/db_init.Dockerfile'
      context: '../'
    entrypoint: 'psql $DATABASE_CONNECTION -f ./db/config.sql -f ./db/tables.sql -f ./db/cargo.testing.sql'
    depends_on:
      - db
    environment:
      - DATABASE_URL
      - DATABASE_TOKEN
      - DATABASE_CONNECTION
  api:
    restart: on-failure
    build:
      dockerfile: docker/db_init.Dockerfile
      context: ../
    # entrypoint: /bin/bash
    environment:
      - DATABASE_URL
      - DATABASE_TOKEN
      - DATABASE_CONNECTION
      - SALT
      - PRIVATE_KEY
      - MAGIC_SECRET_KEY
      - SENTRY_DSN
      - MAILCHIMP_API_KEY
      - LOGTAIL_TOKEN
    depends_on:
      - post_rest
    ports:
      - '8787:8787'
  db:
    build:
      context: ./postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
  ipfs:
    image: ipfs/go-ipfs:v0.10.0 # update this when go-ipfs M1 macs https://github.com/ipfs/go-ipfs/issues/8645

  ipfs_cluster:
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs
    environment:
      CLUSTER_PEERNAME: cluster
      CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_RESTAPI_BASICAUTHCREDENTIALS: test:test
      CLUSTER_RESTAPI_CORSALLOWEDMETHODS: GET,POST,OPTIONS
      CLUSTER_RESTAPI_CORSALLOWEDHEADERS: authorization
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
