services:
  devcontainer:
    restart: on-failure
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    env_file:
      - ../.env
      - ./docker-dev.env
    ports:
      - '8787:8787'
      - '4000:4000'

    depends_on:
      - post-rest
      - ipfs-cluster

    volumes:
      - ..:/nft.storage:delegated

    command: /bin/sh -c "while sleep 1000; do :; done"
    stdin_open: true
    tty: true

  post-rest:
    env_file:
      - ../.env
      - ./docker-dev.env

  db:
    env_file:
      - ../.env
      - ./docker-dev.env

  ipfs:
    env_file:
      - ../.env
      - ./docker-dev.env

  ipfs-cluster:
    env_file:
      - ../.env
      - ./docker-dev.env
