services:
  devcontainer:
    user: node
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: ../
    env_file:
      - ../.env
      - ./docker-dev.env
    ports:
      - '8787:8787'
      - '4000:4000'
    init: true
    volumes:
      - ..:/nft.storage:delegated
      - /var/run/docker.sock:/var/run/docker-host.sock
