name: cron
on:
  push:
    branches:
      - main
    paths:
      - 'packages/cron/**'
      - '.github/workflows/cron.yml'
      - 'yarn.lock'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/cron/**'
      - '.github/workflows/cron.yml'
      - 'yarn.lock'

jobs:
  lint:
    name: lint cron
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: bahmutov/npm-install@v1
      - run: yarn workspace cron lint

  check:
    name: Typecheck cron
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: bahmutov/npm-install@v1
      - run: yarn workspace nft.storage install
      - run: yarn workspace cron install
      - run: ls -alh node_modules | grep 'nft.storage' || true
      - run: ls -alh packages/cron/node_modules | grep 'nft.storage' || true
      - run: ls -alh packages/client || true
      - run: ls -alh packages/client/dist || true
      - run: yarn workspace cron typecheck

  test:
    name: Test cron
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - name: Test (ES)
        run: '[[ -z "${NFT_STORAGE_API_KEY}" ]] && yarn --cwd packages/cron test || echo "NFT_STORAGE_API_KEY is empty"'
        env:
          NFT_STORAGE_API_KEY: ${{ secrets.NFT_STORAGE_API_KEY }}
