name: migration (TokenAsset status in task queue)

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  migrate:
    name: Migrate TokenAsset status to a task queue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn --cwd packages/database install

      - name: Run job
        env:
          FAUNA_KEY: ${{ secrets.FAUNA_KEY }}
          NIFTYSAVE_CLUSTER_KEY: ${{ secrets.NIFTYSAVE_CLUSTER_KEY }}
          NIFTYSAVE_IPFS_API_KEY: ${{ secrets.NIFTYSAVE_IPFS_API_KEY }}
          BATCH_SIZE: 100
          TIME_BUDGET: 1620
          FETCH_TIMEOUT: 10000
        run: node packages/database/src/migrations/2021-08-18-token-asset-queue.js
